repos:
  - repo: local
    hooks:
      - id: make-checklist
        name: Run make checklist
        entry: make checklist
        language: system  # Uses the system’s shell and tools
        types: [python]   # Only runs when Python files are staged